### ISSUE TITLE
middle-mouse-click fails with codemirror on firefox and opera 

### ISSUE THREAD

**Issue by KaiMartin** [albertgasset/dokuwiki-plugin-codemirror#15]
Middle mouse button paste fails on my desktops in firefox/iceweasel and opera. Most of the time nothing happens. Firefox sometimes (but not always) behaves as if the back button was pressed. Opera sometimes segfaults.
However, middle mouse button paste works as expected in chromium, konqueror and rekonq. 

* firefox version:  31.4.0
* opera version: 12.6
* rekonq version: 0.9.2
* konqueror version: 14.0.2
* platform:  linux 3.16.0.4-amd64, debian testing/jessie, upgraded weekly

BTW, thank you for the very useful plugin! I'd be pleased if it would be integrated in dokuwiki main someday.

---<)kaimartin(>---

**Comment by albertgasset** [comment]
Unfortunately, it's not possible to fix this. Firefox doesn't allow access to the clipboard from Javascript.
See https://groups.google.com/forum/#!msg/CodeMirror/zjgIFMPBjrw/KpSrYfucdEoJ
