### ISSUE TITLE
no autoresize of the codemirror textarea

### ISSUE THREAD

**Issue by thej4ck** [albertgasset/dokuwiki-plugin-codemirror#16]
codemirror textarea is not resizable. I get a fixed textarea oh 300px heigth directly in HTML (not even a css rule...)

<div class="CodeMirror cm-s-default CodeMirror-wrap" style="height: 300px; font-size: 14px;">

is pretty useless: i've got a big screeen and a 500x300 textarea
![image](https://cloud.githubusercontent.com/assets/5577620/6018810/ed0c5ddc-ab99-11e4-8ffb-2b4fb22cfc0a.png)

**Comment by albertgasset** [comment]
The width of the editor is limited by the theme. The height can be changed by using the arrow icons below the editor.

**Comment by bkidwell** [comment]
I submitted a pull request to resolve this. #69
