### ISSUE TITLE
When i click Edit Button, shown nothing, the whole page is blank

### ISSUE THREAD

**Issue by kenxausten** [albertgasset/dokuwiki-plugin-codemirror#24]
When i click Edit Button, shown nothing, the whole page is blank

**Comment by Werkov** [comment]
I observed same behavior. It has to do something with server configuration. I did try exact clone of the whole Dokuwiki instance on different machine and it worked as expected. Alas, I do not have access to logs of the other machine, so I'm not able to provide additional information.

**Comment by moni-moni** [comment]
Ahoi!

I had the same problem, but in the Dokuwiki we use in the company, it occurred only on pages with excessive use of code blocks. (<code></code>)
When I remove several code blocks, we are able to edit the page again. Also, editing only one single chapter of the page is always working with the codemirror plugin.
But when I want to edit the whole page, I have to disable the codemirror plugin.

**Comment by LeDistordu** [comment]
i have this problem since "Detritus"

**Comment by albertgasset** [comment]
I've released a new version that fixes the issue for Detritus.
