### ISSUE TITLE
How to make offsets in code smaller

### ISSUE THREAD

**Issue by AndreWin** [albertgasset/dokuwiki-plugin-codemirror#25]
Hello!
I typed in my dokuwiki:
```
<code>
for t in [1, 2, 3, 4, 5]:
     print(t)
</code>
```
After I pressed preview button, I saw that code offset is too big:
![code offset](https://cloud.githubusercontent.com/assets/7497378/7103172/69e79bbc-e0a3-11e4-8b4d-429485784025.png)
How can I make this offset smaller?
Thanks in advance.

**Comment by albertgasset** [comment]
Hi!
The resulting HTML is rendered by Dokuwiki, not the Codemirror plugin. I don't know Dokuwiki has any setting to change the indentation of code blocks. Have you tried using explicit spaces instead of tabs?

**Comment by AndreWin** [comment]
Sorry, it appears to me that you are mistaken. I had to edit /lib/plugins/codemirror/dist/script.min.js and replace at this file 8 spaces to 4 spaces. So the problem is in codemiror plugin, not in dokuwiki. Only after that I have normal offset. As for using spaces unstead of tabs, this way works, but not comfortable.
Best regards, Andrei.
