### ISSUE TITLE
mousebuffer paste does not work

### ISSUE THREAD

**Issue by JOJ0** [albertgasset/dokuwiki-plugin-codemirror#26]
Hi Albert,
pasting stuff from the mousebuffer with middle mouse button into the editor windows does not work with enabled codemirror plugin. If we use the standard dokuwiki editor, pasting with middle mouse button works.

system is fedora19, same issue on fedora20.
browsers are firefox in versions: 34, 37
do you need more information about the system? I will provide it.

is it basically supposed to work? or do you catch middle mouse button for something else?

hope you can help us with this issue, we just upgraded our dokuwiki to the newest hrun version and find your codemirror editor pretty neat and useful :)

all the best
Jojo@LINBIT Vienna

**Comment by albertgasset** [comment]
Hi JOJ0,

This is a known issue/limitation of CodeMirror and Firefox: https://github.com/codemirror/CodeMirror/issues/931
It seems there's no solution for now :-(

**Comment by JOJ0** [comment]
Hey Albert, thanks for the quick response! Appreciated!
I have another idea to solve this issue. If we could disable codemirror on a per user basis it would work for all of us. 
This is actually off topic now but I am askin anyway. Are you aware of any hackish way to enable/disable plugins for certain users?

I just found out that the it's all text plugin also does not work.
I already found this https://github.com/codemirror/CodeMirror/issues/2827
marijnh states that this could be solved with "special-case code in the add-on"
Which I do not understand what it means.

Anyway, I think codemirror enabled and a working it's all text would be fine for all of my colleagues.
If you can point me in the right direction I would be thankful. But actually this is not your concern anymore! ;-)
Thanks a lot!!!
all the best
Jojo

**Comment by albertgasset** [comment]
Hi JOJ0,

I've implemented switching between the native editor and CodeMirror. I hope this helps.

**Comment by JOJ0** [comment]
Hey Albert,
this is a great solution! Now it suits the needs of all of my colleagues!
Thanks so much for your efforts!
all the best
Jojo

PS: I hope I don't reopen this issue with this comment! If yes, sorry!
