### ISSUE TITLE
"Linux Paste" don't work

### ISSUE THREAD

**Issue by moz0817** [albertgasset/dokuwiki-plugin-codemirror#36]
The linux typical insert with middle mouse button don't work. 
It's a bug or a feature? ;-)

**Comment by albertgasset** [comment]
It's a Firefox bug, sadly. See https://bugzilla.mozilla.org/show_bug.cgi?id=846674

**Comment by moz0817** [comment]
Hi,

It could'nt be a firefox bug, 'cause in any other web input field I can use the middle mouse button. The problem occurs only in your editor window.
Remember that I mean the special linux clipboard. The usual pase (with ctrl-v) works faultless.

Greatings
Matthias

 Am 20-Sep-2015 23:16:55 +0200 schrieb notifications@github.com: 

It's a Firefox bug, sadly. See https://bugzilla.mozilla.org/show_bug.cgi?id=846674

**Comment by albertgasset** [comment]
Regular input fields work because they are handled natively by the browser. It's a Firefox bug and there are no workarounds, sorry. See the discussion on CodeMirror: https://github.com/codemirror/CodeMirror/issues/931

**Comment by moz0817** [comment]
... ok I got it now ;-) 

I was a little confused, because I used a long time the ACEEDITOR. 
Now I remember that there a second middle mouse click was needed, to insert from the mousebuffer.

Perhaps you can implement this also. :-)

Thanks

 Am 22-Sep-2015 20:50:21 +0200 schrieb notifications@github.com: 

Regular input fields work because they are handled natively by the browser. It's a Firefox bug and there are no workarounds, sorry. See the discussion on CodeMirror: codemirror/CodeMirror#931
