### ISSUE TITLE
"Smiley replacement" breaks editor

### ISSUE THREAD

**Issue by mnapp** [albertgasset/dokuwiki-plugin-codemirror#38]
I'm witnessing a weird behavior. On a page we have lots of curl commands and explanations for ontology related calls and such. This means we have a lot of text that "looks" like a Smiley but is included in inline code tags or actual code blocks. It appears CodeMirror breaks when some of these elements are tried to be parsed. My Chrome console shows:

```
codemirror.js:5391 Uncaught SyntaxError: Invalid regular expression: /^(?:8-\\\\ 
... 
LOTS of backslashes 
... 
\\\:LOL|FIXME|DELETEME)(?=\W|$)/: RegExp too big
```

To reproduce (put errorpage from the pastebin below into your wiki):
Move cursor to the end of the "--header" section. Right behind ``` ''X-Custom-Header:'' ```
Type a space " ".

This immediately makes the entire preview text disappear and the editor unusable. After a couple of seconds the tab becomes unresponsive. Then after a few more seconds the console shows the error described above and depicted in the screenshots.

When I comment out all entries in "smileys.conf" then the error message says:

```
codemirror.js:5964 Uncaught SyntaxError: Invalid regular expression: /^(?:<->|->|<-|
```

I get the same errors referencing to min.js but I guess that just because of the script compression.

![end_error](https://cloud.githubusercontent.com/assets/4920542/10998905/f45bfd8a-8498-11e5-9112-8f124d89ba57.png)
![more_error](https://cloud.githubusercontent.com/assets/4920542/10998906/f461fd3e-8498-11e5-96de-64f7a3f832b8.png)
![start_error](https://cloud.githubusercontent.com/assets/4920542/10998904/f45b324c-8498-11e5-8fae-195c93693397.png)

http://gfycat.com/BitesizedUnfortunateCirriped

Find the full page that causes this here: http://pastebin.com/SVnNr053

I'm running Detritus with CodeMirror 20150827

**Comment by albertgasset** [comment]
That was hard to reproduce and debug! Thank you for the detailed bug report.
