### ISSUE TITLE
rest of the code mirror stuff?

### ISSUE THREAD

**Issue by mlinchitstest** [albertgasset/dokuwiki-plugin-codemirror#60]
Thanks for the great program. I was thinking about customizing it per instructions on codemirror.net, but the full code mirror package is not included in the plugin. The codemirror folder is empty, so it's not obvious how one would add plugins, change style and so on. Is there a reason why its not there?

**Comment by albertgasset** [comment]
The codemirror code is in a git submodule. See the documentation on how to buld the plugin from source: https://www.dokuwiki.org/plugin:codemirror#development

**Comment by mlinchitstest** [comment]
Thanks.
