### ISSUE TITLE
A single space character at the end of the line does not show in Safari

### ISSUE THREAD

**Issue by maucs5** [albertgasset/dokuwiki-plugin-codemirror#63]
In the screenshot below, there is a letter 'f' and a space after the letter, and the cursor is right after the space character.

However, if I'm editing anywhere in the middle of the line, this problem doesn't occur.

I have tried on a fresh installation of DokuWiki to make sure plugins weren't interfering with this, and this problem doesn't occur on Firefox.

I'm using Safari 10.0.1.

<img width="72" alt="screen shot 2017-01-07 at 6 33 20 pm" src="https://cloud.githubusercontent.com/assets/1415703/21741119/d37e4080-d507-11e6-9209-1ea913c73dad.png">

**Comment by albertgasset** [comment]
This bug is outside the scope of this plugin for Dokuwiki. You better report this bug directly to the CodeMirror project: https://github.com/codemirror/CodeMirror
